# Base URL used when generating links to your pages
# Set to the URL for your site
# baseURL = "https://gupta-aryaman.github.io/"
baseURL = "https://aryaman.space/"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "ARYAMAN.SPACE"
author = "Aryaman Gupta"
copyright = "Copyright © 2024, Aryaman Gupta."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "a corner where ideas, projects, and favorite reads come together"

  favicon = "images/favicon.png"
  
  # image that shows up when the link is shared
  images = ["images/home.jpg"]

  title = "aryaman's batcave"

  # hideMadeWithLine = true

[params.newsletter]
enable = true
title = ""
content = "Want more content like thi? Join my newsletter down below to receive updates to your mailbox"
mailchimpFormUrl = "https://space.us14.list-manage.com/subscribe/post?u=9826b167b24adbcba9091190f&amp;id=f90f480251&amp;f_id=00eb8fe1f0"
mailchimpFormKey = "b_9826b167b24adbcba9091190f_f90f480251"


