[HOME]
    Name = "_index"
    Title = "blog@aryaman"
    URL = "/"
    weight = 1

[BLOG]
    Name = "Blog"
    URL = "/blog"
    weight = 2

[PAPERSHELF]
    Name = "Papershelf"
    URL = "/papershelf"
    weight = 3